# Generated by Django 4.1.7 on 2023-02-18 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_body', models.TextField(max_length=6000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipesNameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='recipesnamemodel',
            index=models.Index(fields=['id'], name='api_recipes_id_94ac41_idx'),
        ),
        migrations.AddConstraint(
            model_name='recipesnamemodel',
            constraint=models.UniqueConstraint(fields=('food_name',), name='unique_food_name'),
        ),
        migrations.AddField(
            model_name='recipesmodel',
            name='food_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recipesnamemodel'),
        ),
    ]
