# Generated by Django 4.1.7 on 2023-02-18 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipesmodel',
            old_name='food_id',
            new_name='food_name',
        ),
    ]
