# Generated by Django 4.1.7 on 2023-02-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_food_id_recipesmodel_food_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipesmodel',
            old_name='recipe_body',
            new_name='ingredient',
        ),
        migrations.AddField(
            model_name='recipesmodel',
            name='quantity',
            field=models.CharField(blank=True, default='Quantity not provided', max_length=200),
        ),
    ]
