# Generated by Django 4.1.7 on 2023-03-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_recipe_body_recipesmodel_ingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipesnamemodel',
            name='description',
            field=models.TextField(blank=True, default='Not described', max_length=6000),
        ),
        migrations.AddField(
            model_name='recipesnamemodel',
            name='image_link',
            field=models.CharField(default='Not given', max_length=1000),
        ),
    ]
