# Generated by Django 4.1.5 on 2023-03-20 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_recipesnamemodel_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipesnamemodel',
            name='image_link',
        ),
    ]
