# Generated by Django 4.1.5 on 2023-03-20 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_recipesnamemodel_image_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipesnamemodel',
            name='description',
        ),
    ]
